In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
import pandas as pd

## DataFrame / Boolean index

In [3]:
# Numpy 에서의  Boolean
a1 = np.random.randint(100,size=(3,4))

a1
a1[[True,False,True],:]
a1[1:,[True,False,True,False]]



array([[ 7, 96, 47, 11],
       [ 7, 84,  6,  8],
       [97, 18, 67, 15]])

array([[ 7, 96, 47, 11],
       [97, 18, 67, 15]])

array([[ 7,  6],
       [97, 67]])

#### loc[[index],[column]] 
    - 열은 True , False 로 지정가능
    - 행은 columns 이름으로 지정가능

In [4]:
df1 = pd.DataFrame(data=np.arange(16).reshape(4,4), index=[10,20,30,40] , columns=list('abcd')  ,dtype=float)
df1
df1.loc[[True,False,False,True],:] # 0열,3열 행은 전체 
df1.loc[[True,False,False,True],['a','c']]  # 열 / 행 

a     b     c     d
10   0.0   1.0   2.0   3.0
20   4.0   5.0   6.0   7.0
30   8.0   9.0  10.0  11.0
40  12.0  13.0  14.0  15.0

a     b     c     d
10   0.0   1.0   2.0   3.0
40  12.0  13.0  14.0  15.0

a     c
10   0.0   2.0
40  12.0  14.0

#### iloc [[index],[column]]
#### Numpy 와 DataFrame 차이가 있다.

In [5]:
df1.iloc[[0,2],[True,False,False,True]]
df1.iloc[:,[True,False,False,True]]


a     d
10  0.0   3.0
30  8.0  11.0

a     d
10   0.0   3.0
20   4.0   7.0
30   8.0  11.0
40  12.0  15.0

## Boolean index 조건 검사

In [6]:
# Numpy 의 경우 
a1

b1 = a1[0,:]>50 # [False,True,True,False]
b1
a1[:,b1]

b2 = a1[:,3]%3==0  # [True,True,False]
b2
a1[b2,:]

array([[ 7, 96, 47, 11],
       [ 7, 84,  6,  8],
       [97, 18, 67, 15]])

array([False,  True, False, False])

array([[96],
       [84],
       [18]])

array([False, False,  True])

array([[97, 18, 67, 15]])

### Pandas DataFrame 의 경우 ( loc 만 가능 )
    - True , False 값이 Series 로 나온다.

In [7]:


df1
df1['c']>9
df1['c']%3==0

a     b     c     d
10   0.0   1.0   2.0   3.0
20   4.0   5.0   6.0   7.0
30   8.0   9.0  10.0  11.0
40  12.0  13.0  14.0  15.0

10    False
20    False
30     True
40     True
Name: c, dtype: bool

10    False
20     True
30    False
40    False
Name: c, dtype: bool

### DataFrame 과 Boolean selection 

In [9]:
df1

df1.loc[df1['c']<8,['d']] # = df1.loc[[True,True,False,False],['d']]

df1.loc[df1['c']>9,['c','d']] # = df1.loc[ [ False,False,True,True],['c','d']]


a     b     c     d
10   0.0   1.0   2.0   3.0
20   4.0   5.0   6.0   7.0
30   8.0   9.0  10.0  11.0
40  12.0  13.0  14.0  15.0

d
10  3.0
20  7.0

d
10  3.0
20  7.0

c     d
30  10.0  11.0
40  14.0  15.0

c     d
30  10.0  11.0
40  14.0  15.0

### numpy 에서 Boolean index
    - 아래는 ar1 에서 5보다 큰 수를 
    - ar1[ar1>5] 하여 출력한 것.
    
    - ar1 에서 5보다 큰 수 가 1차원 벡터로 출력된다.

In [14]:
ar1 = np.random.randint(10 , size=(4,4))
ar1
ar2 =ar1>5
ar2
ar1[ar2]

array([[2, 2, 0, 8],
       [7, 6, 3, 0],
       [3, 0, 6, 7],
       [5, 2, 8, 2]])

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

array([8, 7, 6, 6, 7, 8])

### Pandas 에서 Boolean index
    - numpy 와 마찬가지로 조건식을 [] 에넣고 
    - []조건에 맞는 value 들만 출력된다.
    
    - 단, Numpy 와 다르게 DataFrame 형식을 유지하고,
    - 조건에 맞지 않는 value는 NaN 으로 표시된다. 

In [17]:
df1
df1>2
df1[df1>2]

a     b     c     d
10   0.0   1.0   2.0   3.0
20   4.0   5.0   6.0   7.0
30   8.0   9.0  10.0  11.0
40  12.0  13.0  14.0  15.0

a      b      c     d
10  False  False  False  True
20   True   True   True  True
30   True   True   True  True
40   True   True   True  True

a     b     c     d
10   NaN   NaN   NaN   3.0
20   4.0   5.0   6.0   7.0
30   8.0   9.0  10.0  11.0
40  12.0  13.0  14.0  15.0

## 실습
    - pandas_data3.txt 를 읽으시오.
    - 1. final이 40점 이상인 학생의 수 
    - 2. 처음부터 5명까지 중 2학년의 수 
    - 3. att 이 5점이하인 학생의 기말 점수를 구하고, 그 점수들의 평균
    - 4. proj 가 100점인 학생의 mid , final , att 점수
    - 5. att 이 5점이상 , proj가 90점 이상인 학생 name 
    
    - len() 을 이용해 열의수, 행의수를 사용하라
    - len(list(d1)) = 열의 수 
    - len(d1) 행의 수
   

In [113]:
df1 = pd.read_table('pandas_data3.txt' , index_col=0)



#2 
#df2.iloc[:5][df2['year']==2]

#3

df1.loc[df1['att']<5]['final'].mean()

#4

#df1.loc[df1['proj']==100],['mid','final','att']


#5 
#df2[att>5 , proj>90] 

34.333333333333336

mid  final  att
name                   
choi9    21     33    3
choi10   16     50   10

## 실습 풀이

In [134]:
# 1 
# np.sum(df1['final']>=40)

# df2 = df1.loc[df1['final']>=40]
# #len(df2)

# # 2  df1['year'==2]
# s1 =df1['year']==2
# np.sum(s1.iloc[:5])

# # 3 

# df1.loc[df1['att']<=5,['final','att']]

# df1.loc[df1['att']<=5,'final'].mean()

# 4  df1['proj']==100 인 'mid','att','final' 점수 

#df1.loc[df1['proj']==100,['mid','att','final','proj']]

# 5  att>=5 , proj>=90 인 학생의 name

b1 = df1['att']>=5
b2 = df1['proj']>=90  
# 조건을 2개 만들고 & 으로 조건을 통합하라 
df2 = df1.loc[(b1)&(b2)]
list(df2.index)

['kim3', 'kim9', 'lee5', 'park6', 'choi10', 'kim4', 'lee2']