In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## save and load text 

    - 파일으로 부터 데이터를 가져오는 방법
    - save ( fname = 파일명 , X= save 할 객체 , fmt = 정수or실수 , delimiter = 구분방법 ( '\t , \n ..) 

In [4]:
import numpy as np
import random


In [15]:
a1 = np.random.randint(100 , size=(5,10))
a2 = np.random.normal(0,3 , size=(5,10))
a1
a2


np.savetxt( fname ='file1_int_v2.txt' , X=a1 , fmt='%d' , delimiter='\t')
np.savetxt( fname ='file2_float_v2.txt' , X=a1 , fmt='%.2f' , delimiter=',')

array([[75, 48, 96, 10, 40, 48, 33, 45, 96, 11],
       [74, 71, 83, 21, 25, 33, 16, 67, 97, 75],
       [19, 29, 66, 40, 22, 64, 97, 63, 50, 78],
       [99, 69, 36, 67, 36, 22, 36, 71, 66,  7],
       [66, 57, 10, 86, 96, 58, 72, 74, 27, 69]])

array([[ 0.60423768,  0.89510812,  0.97104505, -0.79894857, -4.15427691,
        -1.37714007, -0.31945034,  1.72560043,  0.45644334, -3.2265008 ],
       [ 2.70580894, -1.36559217, -4.42442976, -0.97371072,  2.05556911,
        -2.96827422, -2.52837267,  2.76842196, -1.53318703, -3.56945297],
       [-1.2679149 , -4.02772548,  4.54721991,  0.02215269,  4.03451987,
         2.07126646,  1.19125502,  2.24759311,  1.90015579,  3.09942314],
       [ 1.28490162, -3.80501559,  0.04278956,  1.28459657, -0.42975225,
         4.49215859, -3.53018329, -3.24167444,  0.74409524, -1.25268516],
       [ 0.70740914, -3.55628917, -4.13947216, -1.70188355, -1.05620392,
         0.36675825, -1.48033768,  1.75032986,  2.27532073,  0.56018398]])

#### nan 을 포함시켜서 save 하기

    - nan 은 float 이기 때문에 astype 으로 int 을 float 으로 바꿔야한다
    - astype 은 리턴이기때문에 같은 변수명으로 지명한다 

In [32]:
a3 = np.random.randint(100 , size=(5,10))
a3 =a3.astype(float) # nan 은 float 타입이기때문에 int 인 a3 를 float 으로 변형 
a3[[1,2],[1,2]] = np.nan
a3

np.savetxt( fname = 'file3_nan.txt', X=a3 , fmt="%.2f" , delimiter = ',')

array([[37.,  9., 33., 39., 98., 67., 86., 29., 60., 67.],
       [12., nan, 77., 56., 59., 21., 47., 52., 42.,  5.],
       [32., 90., nan, 89., 91., 71., 68., 71., 69., 37.],
       [32., 79., 55., 97., 49., 39., 71., 30., 20., 97.],
       [32.,  0., 77., 74.,  1., 35., 75., 41., 45., 37.]])

## load txt
    - np.loadtxt( fname='파일명' , dtype= 데이터타입 , delimiter= ' 구분방법 ' , usecols= 따로가져오기 [ 행 ]
    - 만약 불러올 파일이 손상되었거나 비어있는 상태로 load 를한다면 에러 발생
    - 하지만 genfromtxt 로 불러온다면 비어있는 상태를 원하는 데이터로 변환할 수있다. ( filing_values = '' 파라미터 를 사용한다)

In [43]:
a4 = np.loadtxt( fname='file3_nan.txt' , dtype=float , delimiter = ',' , usecols=[0,1,2])

a4
np.isnan(a4)
np.isnan(a4).sum()

array([[37.,  9., 33.],
       [12., nan, 77.],
       [32., 90., nan],
       [32., 79., 97.],
       [32., 74.,  1.]])

array([[False, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

2

## 실습 1

    - 파일을 읽고
    - 1. 각 행 별 평균을 구하라
    - 2. 50보다 큰 수들의 평균을 구하라

In [57]:
a1 = np.loadtxt( fname='file1_int_v2.txt' , dtype=int , delimiter='\t')

a1
a1.mean(axis=1) # 각 행들의 평균 

a1[a1>50].mean() # fancy index 를 사용한방법 

t1 = np.where(a1>50) # np.where 를 사용한방법
a1[t1]

array([[75, 48, 96, 10, 40, 48, 33, 45, 96, 11],
       [74, 71, 83, 21, 25, 33, 16, 67, 97, 75],
       [19, 29, 66, 40, 22, 64, 97, 63, 50, 78],
       [99, 69, 36, 67, 36, 22, 36, 71, 66,  7],
       [66, 57, 10, 86, 96, 58, 72, 74, 27, 69]])

array([50.2, 56.2, 52.8, 50.9, 61.5])

76.0

array([75, 96, 96, 74, 71, 83, 67, 97, 75, 66, 64, 97, 63, 78, 99, 69, 67,
       71, 66, 66, 57, 86, 96, 58, 72, 74, 69])

## 실습 2

    - 파일을 읽고
    - missing value 가 없는 행들의 , 각 행 별 최대값 과 그 index 를 구하여라

In [64]:
a1 = np.genfromtxt( fname='file3_nan.txt' , dtype=float , delimiter='\t')

a1
np.isnan(a1).sum(axis=1)

array([nan, nan, nan, nan, nan])

AxisError: axis 1 is out of bounds for array of dimension 1