# 버전 체크

In [2]:
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
numpy 1.18.1
pandas 1.0.1


# 8주차

## 보충설명 (numpy unicode)

In [15]:
a1=np.array(['ab','cde'])
a1
a1.nbytes
a2=np.array(['ab','cde', 12,4.12])
a2
a2.nbytes
a3=np.array([['ab','데이터과학부'], [12,4.12]])
a3
a3.nbytes

array(['ab', 'cde'], dtype='<U3')

24

array(['ab', 'cde', '12', '4.12'], dtype='<U4')

64

array([['ab', '데이터과학부'],
       ['12', '4.12']], dtype='<U6')

96

## 과제1

In [25]:
a1=np.genfromtxt(fname='proj1.txt', dtype=float, delimiter='\t')
##
a1
# 1)
np.isnan(a1).sum(axis=1)
# 2)
a1[a1==a1].mean()

array([[-3.479,    nan, -0.892,  1.407, -3.779, -3.188,  5.818,  2.207],
       [ 7.918,    nan,  0.114, -0.194,  3.017,  1.774,  1.074,  0.087],
       [ 2.162,  2.501,  7.297,  1.402, -3.236, -2.566,  2.718,  1.323],
       [ 2.721, -0.122,    nan, -3.45 ,  2.003,  2.442, -2.052,    nan],
       [ 2.171,  0.264, -3.167, -0.543, -1.46 ,  1.232,  1.748, -0.661],
       [-3.479,  3.42 , -0.892,  1.407, -3.779, -3.188,  5.818,  2.207],
       [ 7.918,  1.12 ,  0.114, -0.194,  3.017,  1.774,  1.074,    nan],
       [ 2.162,  2.501,  7.297,  1.402, -3.236,    nan,  2.718,  1.323],
       [ 2.721, -0.122,    nan, -3.45 ,  2.003,  2.442, -2.052,  1.873],
       [ 2.171,  0.264, -3.167, -0.543, -1.46 ,  1.232,  1.748, -0.661],
       [ 2.162,  2.501,  7.297,  1.402, -3.236, -2.566,  2.718,  1.323],
       [ 2.721, -0.122,    nan, -3.45 ,  2.003,  2.442, -2.052,    nan],
       [ 2.171,  0.264, -3.167, -0.543, -1.46 ,  1.232,  1.748, -0.661],
       [-3.479,    nan, -0.892,  1.407, -3.779, -3.

array([1, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1])

0.7589449541284403

## 과제2

In [26]:
s1=pd.Series([1,2,3,4.11,5,6], index=list('a1b2c3'), dtype=float, name='ds')
s1.index.name='ds_index'
s1
s1=s1.astype(int)
s1

ds_index
a    1.00
1    2.00
b    3.00
2    4.11
c    5.00
3    6.00
Name: ds, dtype: float64

ds_index
a    1
1    2
b    3
2    4
c    5
3    6
Name: ds, dtype: int32

# 9주차

## 실습1

In [8]:
s1=pd.Series(np.random.randint(0,10,size=5), index=range(1,6))
s1
a1=s1.values
a1
a2=a1[a1>=3]
a2
a2.mean()

1    5
2    1
3    2
4    1
5    8
dtype: int32

array([5, 1, 2, 1, 8])

array([5, 8])

6.5

## series indexing

In [ ]:
sr1=pd.Series(data=[1,2,3,4,5], index=list('abcde'), dtype=float, name='sr1')
print(sr1)

print("## indexing (값 하나) => return scalar (하나의 값)")
print(sr1.loc['c']) 
print(sr1['c']) #위 코드와 동일
sr1.loc['c']=-3.2
sr1['c']=-3.2 #위 코드와 동일   
print(sr1)

print("## indexing (값 둘 이상) => return series")
# print(sr1.loc['a','e'])  에러발생
print(sr1.loc[['a','e']])  
print(sr1[['a','e']]) #위 코드와 동일
sr1.loc[['a','e']]=-5
sr1[['a','e']]=-5 #위 코드와 동일
print(sr1)

print("## indexing (값 하나) => return series")
print(sr1.loc[['a']])
print(sr1[['a']]) #위 코드와 동일
sr1.loc[['a']]=10
sr1[['a']]=10 #위 코드와 동일
print(sr1)

In [ ]:
sr1=pd.Series(data=[1,2,3,4,5], index=list('abcde'), dtype=float, name='sr1')
print(sr1)

print("## indexing (값 하나)")
print(sr1.iloc[2]) # 하나의 값
sr1.iloc[2]=-3.2
print(sr1)

print("## indexing (값 둘 이상)")
print(sr1.iloc[[1,2]]) # series
sr1.iloc[[1,2]]=-5
print(sr1)

## series slicing

In [ ]:
sr1=pd.Series(data=[1,2,3,4,5], index=[3,7,4,5,6], name='sr1')
print(sr1)

print('##################')
print(sr1.iloc[3])
print(sr1.loc[3])
print('##################')
print(sr1.iloc[3:5])
print(sr1.loc[3:5])
print('##################')
print(sr1.iloc[3::2])
print(sr1.loc[7::2])

## 실습2

In [11]:
s1=pd.Series(np.arange(10), index=list('e1d2c3b4a5'))
s1
s1.loc['d']
s1.loc[['5']]
s1.loc['d':'b':2]

s1.iloc[2]
s1.iloc[[-1]]
s1.iloc[2:7:2]

e    0
1    1
d    2
2    3
c    4
3    5
b    6
4    7
a    8
5    9
dtype: int32

2

5    9
dtype: int32

d    2
c    4
b    6
dtype: int32

2

5    9
dtype: int32

d    2
c    4
b    6
dtype: int32

## series creation

In [11]:
## 정규분포에서 데이터 가져오기
sr1=pd.Series(data=np.random.normal(0,2,size=(4)), name='sr1')
sr1
## 랜덤한 정수가져오기
sr2=pd.Series(data=np.random.randint(100,size=(4)), name='sr2')
sr2
## 주어진 list에서 랜덤하게 sampling 하여 가져오기
sr3=pd.Series(data=np.random.choice(list('erferwe'),size=(4)), name='sr3')
sr3

0   -1.157260
1    1.887921
2    0.729937
3   -0.054774
Name: sr1, dtype: float64

0    39
1    75
2    18
3    28
Name: sr2, dtype: int32

0    w
1    e
2    r
3    r
Name: sr3, dtype: object

## 하나의 series내 function

In [28]:
sr1=pd.Series(data=[3,2,1,4,5], index=list('abcde'), name='sr1')
sr1
sr1%3
# mean
sr1.mean()
np.mean(sr1)
print('###############')
#pd.mean() # not available: pd.mean(sr1))
sr1.max()
sr1.sum()
print('###############')
sr1.argmax()
sr1.idxmax()

a    3
b    2
c    1
d    4
e    5
Name: sr1, dtype: int64

a    0
b    2
c    1
d    1
e    2
Name: sr1, dtype: int64

3.0

3.0

###############


5

15

###############


4

'e'

## 하나의 series내 comparison & boolean index

In [17]:
sr2=pd.Series(data=np.random.randint(10,size=(6)), name='sr2')
sr2
sr2>4
sr2[sr2>4]

0    2
1    4
2    7
3    0
4    1
5    5
Name: sr2, dtype: int32

0    False
1    False
2     True
3    False
4    False
5     True
Name: sr2, dtype: bool

2    7
5    5
Name: sr2, dtype: int32

## series sort

In [79]:
print("#### sort data")
s1=pd.Series(data=[5,2,4,1,3], index=list('abcde'))
s1
s1.sort_values()
s1
s1.sort_values(inplace=True)
s1
s1=pd.Series(data=[5,2,4,1,3], index=list('abcde'))
s1=s1.sort_values()
s1
print("#### sort index")
s1=pd.Series(data=[5,2,4,1,3], index=list('cdabe'))
s1
s1=s1.sort_index()
s1

#### sort data


a    5
b    2
c    4
d    1
e    3
dtype: int64

d    1
b    2
e    3
c    4
a    5
dtype: int64

a    5
b    2
c    4
d    1
e    3
dtype: int64

d    1
b    2
e    3
c    4
a    5
dtype: int64

d    1
b    2
e    3
c    4
a    5
dtype: int64

#### sort index


c    5
d    2
a    4
b    1
e    3
dtype: int64

a    4
b    1
c    5
d    2
e    3
dtype: int64

## series 간 function

In [2]:
print("## index 동일")
sr1=pd.Series(data=[1,2,3,4,5], index=list('abcde'))
sr2=pd.Series(data=[5,2,4,3,1], index=list('abcde'))
sr1
sr2
sr1*sr2
sr1>sr2

print("## index 다름 (순서만)")
sr1=pd.Series(data=[1,2,3,4,5], index=list('abcde'))
sr2=pd.Series(data=[5,2,4,3,1], index=list('daecb'))
sr1
sr2
sr1+sr2
sr1>sr2

## index 동일


a    1
b    2
c    3
d    4
e    5
dtype: int64

a    5
b    2
c    4
d    3
e    1
dtype: int64

a     5
b     4
c    12
d    12
e     5
dtype: int64

a    False
b    False
c    False
d     True
e     True
dtype: bool

## index 다름 (순서만)


a    1
b    2
c    3
d    4
e    5
dtype: int64

d    5
a    2
e    4
c    3
b    1
dtype: int64

a    3
b    3
c    6
d    9
e    9
dtype: int64

ValueError: Can only compare identically-labeled Series objects

In [3]:
sr1=pd.Series(data=[3,2,1,4,5], index=list('cdbef'), name='sr1')
sr2=pd.Series(data=[3,2,1,4,5], index=list('abcde'), name='sr2')
sr3=sr1+sr2
print(sr3)
print(sr3.isnull())
print(sr3.notnull())
print(np.sum(sr3.isnull()))
print(sr3[sr3.notnull()])
print(sr1>sr2)

a    NaN
b    3.0
c    4.0
d    6.0
e    9.0
f    NaN
dtype: float64
a     True
b    False
c    False
d    False
e    False
f     True
dtype: bool
a    False
b     True
c     True
d     True
e     True
f    False
dtype: bool
2
b    3.0
c    4.0
d    6.0
e    9.0
dtype: float64


ValueError: Can only compare identically-labeled Series objects

## Series 수학함수

In [41]:
sr1=pd.Series(data=[1,2,3,4,5], index=list('abcde'), name='sr1')
sr1
np.exp(sr1)
np.power(sr1,2)

a    1
b    2
c    3
d    4
e    5
Name: sr1, dtype: int64

a      2.718282
b      7.389056
c     20.085537
d     54.598150
e    148.413159
Name: sr1, dtype: float64

a     1
b     4
c     9
d    16
e    25
Name: sr1, dtype: int64

## 실습3

In [41]:
sr1=pd.Series(np.random.randint(10,size=10))
sr1
sr2=sr1*3+1
sr2
sr3=sr2[sr2%5==0]
sr3
ar1=np.array(sr3.index)
ar1.sum()

0    1
1    5
2    9
3    9
4    7
5    3
6    9
7    3
8    9
9    7
dtype: int32

0     4
1    16
2    28
3    28
4    22
5    10
6    28
7    10
8    28
9    22
dtype: int32

5    10
7    10
dtype: int32

12

## 실습4

In [56]:
sr1=pd.Series(np.random.randint(100,size=6), index=list('abcdef'))
sr1
sr1=sr1.sort_values(ascending=False)
sr1
sr1.index
sr1.index[1]

a    93
b    57
c    27
d    28
e    67
f    35
dtype: int32

a    93
e    67
b    57
f    35
d    28
c    27
dtype: int32

Index(['a', 'e', 'b', 'f', 'd', 'c'], dtype='object')

'e'

## 실습5

In [77]:
s1=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s1
s2=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s2
s3=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s3

s4=s1+s2+s3
s4
s5=s4[s4.notnull()]
s5.sum()

b    7
d    8
h    9
g    5
a    1
dtype: int32

d    9
g    4
e    2
a    8
b    2
dtype: int32

b    4
d    9
g    3
f    6
c    1
dtype: int32

a     NaN
b    13.0
c     NaN
d    26.0
e     NaN
f     NaN
g    12.0
h     NaN
dtype: float64

51.0

## 과제1

In [3]:
sr1=pd.Series(data=np.random.randint(100,size=5), index=np.random.randint(100,size=5))
print("## sr1")
sr1
print("## sr1%2==0")
sr2=sr1[sr1%2==0]
sr2
print("## index sum")
np.sum(sr2.index)

## sr1


8     58
99    61
95    62
81    11
26    10
dtype: int32

## sr1%2==0


8     58
95    62
26    10
dtype: int32

## index sum


129

## 과제2

In [10]:
sr1=pd.Series(data=np.random.randint(100,size=5), index=list('abcde'))
print("## sr1")
sr1
sr1[sr1>=60]=-100
sr1

## sr1


a    71
b    61
c    26
d    39
e    39
dtype: int32

a   -100
b   -100
c     26
d     39
e     39
dtype: int32

# 10주차

## 실습1

In [4]:
# 방법1
dat=[['aa','suwon',2],['bb','suwon',1],['cc','aju',3]]
d1=pd.DataFrame(data=dat, index=['st1','st2','st3'], columns=['name','univ','rank'])
d1
# 방법2
dat={'name':['aa','bb','cc'],'univ':['suwon','suwon','aju'], 'rank':[2,1,3]}
d2=pd.DataFrame(data=dat, index=['st1','st2','st3'])
d2
# 방법32
d3=pd.read_table('prac1.txt', index_col=0, sep='\t')
d3

name   univ  rank
st1   aa  suwon     2
st2   bb  suwon     1
st3   cc    aju     3

name   univ  rank
st1   aa  suwon     2
st2   bb  suwon     1
st3   cc    aju     3

name   univ  rank
st1   aa  suwon     2
st2   bb  suwon     1
st3   cc    aju     3

## 실습2

In [6]:
dat={'a':[1,2,3],'b':[2,3,4], 'c':[3,4,5]}
d1=pd.DataFrame(data=dat, index=['g','k','p'])
d1
d1['b']=[11.1,22.0,33.0]
d1['c']=d1['c'].astype(float)
d1.index=['aa','bb','cc']
d1.index.name='index'
d1.columns.name='column'
d1

a  b  c
g  1  2  3
k  2  3  4
p  3  4  5

column  a     b    c
index               
aa      1  11.1  3.0
bb      2  22.0  4.0
cc      3  33.0  5.0

## 실습3

In [9]:
d1=pd.read_table('pandas_data1.txt', sep='\t', index_col=0, engine='python')
## 1)
d1.loc[:'김열']
## 2)
d1.loc['최하나','기말']
## 3)
# series
d1.loc['김다섯']
# dataframe
d1.loc[['김다섯']]
## 4)
d1.iloc[:7]['학년']
## 5)
d1.loc[['이여섯','최아홉'],'중간':'출석']
## 6)
d1.iloc[-5:][['출석','과제']]

성별  학년  중간  기말  출석  과제
이름                         
김둘   여자   1  12  36   5  75
김셋   남자   2  17  20   5  96
김여섯  남자   2  28  20   4  83
김일곱  남자   2  20  44   6  82
김여덜  여자   1  20  24   8  88
김아홉  남자   3  23  45  10  92
김열   남자   3  16  47   5  83

39

성별    남자
학년     2
중간    24
기말    18
출석     6
과제    84
Name: 김다섯, dtype: object

성별  학년  중간  기말  출석  과제
이름                         
김다섯  남자   2  24  18   6  84

이름
김둘     1
김셋     2
김여섯    2
김일곱    2
김여덜    1
김아홉    3
김열     3
Name: 학년, dtype: int64

중간  기말  출석
이름             
이여섯  22  38   7
최아홉  21  33   3

출석  과제
이름         
김다섯   6  84
이하나   5  79
이둘    8  98
이셋    4  79
이넷   10  89