# Tensorflow 1.x 학습하기

In [62]:
# Tensorflow version 확인하기

import tensorflow as tf
print(tf.__version__)

2.3.1


In [15]:
# Tensorflow 1.x code 구현

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tfs=tf.InteractiveSession()
c1=tf.constant(10., tf.float64, name='x')
print(c1)
tfs.run(c1)

Tensor("x_7:0", shape=(), dtype=float64)


10.0

In [22]:
c2=tf.constant(5., name='y')
c3=tf.constant(7., tf.float32, name='z')
op1=tf.add(c2, c3)
tfs.run(op1)

<tf.Tensor 'z_6:0' shape=() dtype=float32>

In [24]:
op2=tf.multiply(c2,c3)
tfs.run(op2)

35.0

In [30]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

A=tf.constant([ [1,2,3], [4,5,6]])

x=tf.constant([1,0,1])

print(A.get_shape())

(2, 3)


In [31]:
x=tf.expand_dims(x,1)
print(x.get_shape())

(3, 1)


In [32]:
b=tf.matmul(A,x)
sess=tf.InteractiveSession()
print('matmul result:\n {}'.format(b.eval()))
sess.close()

matmul result:
 [[ 4]
 [10]]


In [36]:
# 변수(Variable) - 변수생성 및 초기화 &세션에서 초기화 연산을 명시적으로 수행

init_val=tf.random_normal((1,5),0,1)
var=tf.Variable(init_val, name='var')
print("pre run:\n {}".format(var))

init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    post_var=sess.run(var)
    
print("post run:\n {}".format(post_var))

pre run:
 <tf.Variable 'var_3:0' shape=(1, 5) dtype=float32_ref>
post run:
 [[-0.7124264  -0.7117437  -0.14792399 -1.2354933  -1.0660414 ]]


In [70]:
# 플레이스홀더(placeholde) - 데이터 입력을 위한 내장구조

# shpae 인수를 선택적으로 사용 가능, 값이 지정되지 않거나 None으로 지정되면 모든 크기의 데이터 입력 가능
#ph=tf.placeholder(tf.float32, shape(None, 10))

# 플레이스홀더를 정의하면 반드시 입력값을 넣어야 하며 입력데이터는 딕셔너리 형태로 session.run() 메서드에 전달(키는 변수명, 값은 데이터)
#sess.run(s, feed_dict={x: x_data, w: w_data})

import numpy as np
x_data=np.random.randn(5,10)
w_data=np.random.randn(10,1)

with tf.Graph().as_default():
    x=tf.placeholder(tf.float32, shape=(5,10))
    w=tf.placeholder(tf.float32, shape=(10,1))
    b=tf.fill((5,1), -1.)
    xw=tf.matmul(x,w)
    
    xwb=xw + b
    s=tf.reduce_max(xwb)
    with tf.Session() as sess:
        outs=sess.run(s,feed_dict={x:x_data, w:w_data})
    print("outs= {}".format(outs))

outs= 1.3979549407958984


# Tensorflow 2.x 학습하기

### 1. 텐서와 연산

- tf.constant() 함수로 텐서를 만들 수 있다.
- ndarray와 마찬가지로 tf.Tensor는 크기(shape)와 데이터 타입(dtype)을 가짐
- 인덱스 참조도 넘파이와 비슷하게 작동
- 모든 종류의 텐서 연산이 가능


In [4]:
import tensorflow as tf


c1=tf.constant(10) # scalar
print(c1)
c2=tf.constant(5.0)
c3=tf.constant(7.0)
op_1=tf.add(c2,c3)
print(op_1)
op_2=tf.multiply(c2,c3)
print(op_2)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(35.0, shape=(), dtype=float32)


In [5]:
a=tf.constant([[10,10],[11.,1.]])
x=tf.constant([[1.,0.],[0.,1.]])
b=tf.Variable(12.)
y=tf.matmul(a,x)+b
print(y)

tf.Tensor(
[[22. 22.]
 [23. 13.]], shape=(2, 2), dtype=float32)


In [6]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

### indexing

In [8]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [10]:
t[...,1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

### 연산 

In [11]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [12]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [13]:
t @ tf.transpose(t)  # @ 연산은 행렬 곱셈을 의미, tf.matmul()과 동일

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### keras.backend 사용하기

In [14]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

### 넘파이 변환

In [7]:
import numpy as np
a=np.array([2.,4.,5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [8]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [10]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

### 타입 변환

In [24]:
try:
    tf.constant(2.0)+tf.constant(40)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]


In [25]:
try:
    tf.constant(2.0) + t.f
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]


In [26]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### 문자열

In [27]:
tf.constant(b"hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [28]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [29]:
u = tf.constant([ord(c) for c in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

In [30]:
b = tf.strings.unicode_encode(u, "UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [31]:
tf.strings.unicode_decode(b, "UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

In [32]:
p = tf.constant(["Café", "Coffee", "caffè", "咖啡"])

In [33]:
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 2])>

In [36]:
r = tf.strings.unicode_decode(p, "UTF8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232], [21654, 21857]]>

In [37]:
print(r)

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232], [21654, 21857]]>


### 변수(Variable)

In [38]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]]) # 값을 변경할 수 있음.

In [39]:
v.assign(2 * v) # 변수값을 변경할 수 있음.

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [40]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [41]:
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [45]:
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


In [46]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]],
                    updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [47]:
sparse_delta = tf.IndexedSlices(values=[[1., 2., 3.], [4., 5., 6.]],
                                indices=[1, 0])
v.scatter_update(sparse_delta)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

## 텐서배열

In [43]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3., 10.]))
array = array.write(2, tf.constant([5., 7.]))

In [44]:
array.read(1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>