# 1. Tensorflow 1.x 이해

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

v_1=tf.constant([1,2,3,4])
v_2=tf.constant([2,1,5,3])
v_add=tf.add(v_1,v_2)
with tf.Session() as sess:
    print(sess.run(v_add))

Instructions for updating:
non-resource variables are not supported in the long term
[3 3 8 7]


In [2]:
sess=tf.Session()
print(sess.run(v_add))
sess.close()

[3 3 8 7]


In [11]:
## 연산의 예시
tfs=tf.InteractiveSession()

t_1=tf.constant(4)
t_2=tf.constant([4,3,2])
zero_t=tf.zeros([2,3], tf.int32)

print(t_1)
print(t_2)
print(zero_t)

Tensor("Const_4:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(3,), dtype=int32)
Tensor("zeros_1:0", shape=(2, 3), dtype=int32)


In [12]:
print(tf.zeros_like(t_2))
print(tf.ones_like(t_2))
tfs.run(tf.zeros_like(t_2))

Tensor("zeros_like_1:0", shape=(3,), dtype=int32)
Tensor("ones_like_1:0", shape=(3,), dtype=int32)


array([0, 0, 0], dtype=int32)

In [15]:
# 넘파이와 유사하게 브로드캐스트 
t=tf.Variable([[0.,1.,2.],[3.,4.,5.,],[6.,7.,8.]])

print(t*2)
print(t**2)


init=tf.global_variables_initializer()
tfs.run(init)
tfs.run(t*2)

Tensor("mul_6:0", shape=(3, 3), dtype=float32)
Tensor("pow_3:0", shape=(3, 3), dtype=float32)


array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.]], dtype=float32)

In [8]:
# sequence

range_t=tf.linspace(2.0, 5.0, 5)
print(range_t)

Tensor("linspace_1/Slice:0", shape=(5,), dtype=float32)


In [10]:
range_t2=tf.range(10)
print(range_t2)

Tensor("range:0", shape=(10,), dtype=int32)


In [16]:
# Variable 변수의 정의

rand_t=tf.random_uniform([50,50],0,10,seed=0)
t_a=tf.Variable(rand_t)
t_b=tf.Variable(rand_t)

In [24]:
weights=tf.Variable(tf.random_normal([100,100], stddev=2))
bias=tf.Variable(tf.zeros([100], tf.float32), name='biases')

In [25]:
# 변수 초기화
# 선언된 모든 변수는 명시적으로 값을 초기화해야 하므로 변수의 정의에서 초기화 방법을 지정해야 한다.
# 계산 그래프의 정의에서 연산 객체를 선언해 초기화한다.

intial_op=tf.global_variables_initializer()
# 그래프를 실행하는 동안 tf.Variable.initializer를 사용하면 각 변수를 개별적으로 초기화 할 수 있다.
bias=tf.Variable(tf.zeros([100,100]))
with tf.Session() as sess:
    sess.run(bias.initializer)

In [26]:
# 변수 저장 : Saver 클래스를 사용해 모든 변수를 저장할 수 있다. 

saver=tf.train.Saver()


In [27]:
# Placeholder

# x에 대한 플레이스홀더를 정의하고 임의의 4*5 행렬에 대해 feed_dict를 사용해 y=2x를 계산

x=tf.placeholder("float")
y=2*x
data=tf.random_uniform([4,5],10)
with tf.Session() as sess:
    x_data=sess.run(data)
    print(sess.run(y, feed_dict={x:x_data}))   # feed_dict 는 텐서플로 플레이스홀더에 값을 공급하는 역할

[[13.508035   9.100512  14.233702  15.133608   4.6073093]
 [ 2.4462204 14.324924  19.133883  11.854273   2.2185783]
 [ 6.9019775  7.896036  18.042809  10.579325  17.508574 ]
 [14.804514  16.119246   6.4932747  5.0442753  7.771826 ]]


# 2. Tensorflow 2.x 이해

- 텐서플로 1.x API는 심층 신경망과 다른 많은 유형의 머신러닝 프로그램을 나타내는 계산 그래프를 생성하고 조작하는 유연한 방법을 제공
- 텐서플로 2.x.는 더 낮은 수준의 세부 정보를 추상화하는 높은 수준의 API를 제공

In [2]:
# tensorflow 1.x 에서 계산그래프 보기

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

in_a=tf.placeholder(dtype=tf.float32, shape=(2))

def model(x):
    with tf.variable_scope("matmul"):
        W=tf.get_variable("W", initializer=tf.ones(shape=(2,2)))
        b=tf.get_variable("b", initializer=tf.zeros(shape=(2)))
        return x * W + b
    
out_a=model(in_a)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outs=sess.run([out_a],
                 feed_dict={in_a:[1,0]})
    writer=tf.summary.FileWriter("./logs/example/", sess.graph)

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
!tensorboard --logdir=./logs/example

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.3.0 at http://localhost:6007/ (Press CTRL+C to quit)
^C


### numpy처럼 텐서플로 사용하기

In [26]:
# numpy처럼 텐서플로 사용하기
import tensorflow as tf
import numpy as np

t = tf.constant([[1.,2.,3.],[4.,5.,6.]]) # matrix
t

<tf.Tensor 'Const_16:0' shape=(2, 3) dtype=float32>

In [27]:
tf.constant(42)

<tf.Tensor 'Const_17:0' shape=() dtype=int32>

In [28]:
# 크기와 데이터타입을 갖음

t=tf.constant([[1.,2.,3.],[4.,5.,6.]])
t

<tf.Tensor 'Const_18:0' shape=(2, 3) dtype=float32>

In [30]:
# index 
print(t[:,1:])

Tensor("strided_slice_7:0", shape=(2, 2), dtype=float32)


<tf.Tensor 'Const_3:0' shape=(2, 3) dtype=float32>

### Auto graph

- 텐서플로가 그래프를 생성하는 방법은 먼저 파이썬 함수의 코드를 분석하여 for문, while문, if문은 물론 break, continue, return과 같은 제어문을 모두 찾음
- 이 단계를 오토그래프라고 함.
- 텐서플로가 소스코드를 분석하는 이유는 파이썬이 제어문을 찾을 수 있느 방법을 제공하지 않기 때문
- 함수의 코드를 분석한 후 오토그래프는 이 함수의 모든 제어문을 텐서플로 연산으로 바꾼 업그레이된 버전을 만듦

In [5]:
# 오토 그래프 (auto graph) : @tf.function

import tensorflow as tf

def linear_layer(x):
  return 3 * x + 2

@tf.function
def simple_nn(x):
  return tf.nn.relu(linear_layer(x))


def simple_function(x):
	return 3*x

# internal look at the autogenerated code
print(tf.autograph.to_code(simple_nn.python_function, experimental_optional_features=None))

## 2.1 Keras API

### 1. Sequential API

In [8]:
from tensorflow import keras

tf.keras.utils.plot_model(model, to_file='model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


## tf.data.datasets로 훈련하기

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

ModuleNotFoundError: No module named 'tensorflow_datasets'

In [10]:
!pip install tensorflow-datasets

     |████████████████████████████████| 3.5 MB 518 kB/s eta 0:00:01
     |████████████████████████████████| 829 kB 86.8 MB/s eta 0:00:01
     |████████████████████████████████| 44 kB 11.4 MB/s eta 0:00:01
     |████████████████████████████████| 70 kB 34.1 MB/s eta 0:00:01
     |████████████████████████████████| 177 kB 49.0 MB/s eta 0:00:01
     |████████████████████████████████| 95 kB 15.8 MB/s eta 0:00:01
     |████████████████████████████████| 100 kB 37.6 MB/s ta 0:00:01
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=45455bf89d57ed4613ed18a94b648c988f8984fc2afda1172dfdfa4757f2bf9c
  Stored in directory: /Users/byunghwalim/Library/Caches/pip/wheels/54/aa/01/724885182f93150035a2a91bce34a12877e8067a97baaf5dc8
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=c42732697f80b344ba7ec59792339239617460c07259c41f54a752c1f734a85a
  Stored in directory: /Users/byunghwalim/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f

In [12]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [13]:
builders=tfds.list_builders()
print(builders)

['abstract_reasoning', 'accentdb', 'aeslc', 'aflw2k3d', 'ag_news_subset', 'ai2_arc', 'ai2_arc_with_ir', 'amazon_us_reviews', 'anli', 'arc', 'bair_robot_pushing_small', 'bccd', 'beans', 'big_patent', 'bigearthnet', 'billsum', 'binarized_mnist', 'binary_alpha_digits', 'blimp', 'bool_q', 'c4', 'caltech101', 'caltech_birds2010', 'caltech_birds2011', 'cars196', 'cassava', 'cats_vs_dogs', 'celeb_a', 'celeb_a_hq', 'cfq', 'chexpert', 'cifar10', 'cifar100', 'cifar10_1', 'cifar10_corrupted', 'citrus_leaves', 'cityscapes', 'civil_comments', 'clevr', 'clic', 'clinc_oos', 'cmaterdb', 'cnn_dailymail', 'coco', 'coco_captions', 'coil100', 'colorectal_histology', 'colorectal_histology_large', 'common_voice', 'coqa', 'cos_e', 'cosmos_qa', 'covid19sum', 'crema_d', 'curated_breast_imaging_ddsm', 'cycle_gan', 'deep_weeds', 'definite_pronoun_resolution', 'dementiabank', 'diabetic_retinopathy_detection', 'div2k', 'dmlab', 'downsampled_imagenet', 'dsprites', 'dtd', 'duke_ultrasound', 'emnist', 'eraser_multi_r

In [15]:
#name에 지정된 데이터셋을 DatasetInfo 메타데이터와 함께 로드
data, info=tfds.load("mnist", with_info=True, try_gcs=True)
train_data, test_data=data['train'], data['test']
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    version=3.0.1,
    description='The MNIST database of handwritten digits.',
    homepage='http://yann.lecun.com/exdb/mnist/',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
    redistribution_info=,
)



## 2.3 tf.keras와 추정기


### 각 은닉층에 10개의 노드가 있으며, 2개의 은닉층을 가진 DNN 구축

```
classifier = tf.estimator.DNNClassifier(feature_columns=my_feature_columns, # 모델에서 사용하려는 단일 특징을 설명하는 열의 목록
                                       # 각 10개의 노드를 가진 두 은닉층
                                       hidden_units=[10,10],
                                       # 모델은 3개의 부류 중에서 선택
                                       n_classes=3)
```


In [17]:
# MNIST 로드, 크기 변환, 섞기, 배치

import tensorflow as tf
import tensorflow_datasets as tfds

BUFFER_SIZE = 10000
BATCH_SIZE = 64

def input_fn(mode):
  datasets, info = tfds.load(name='mnist',
                                with_info=True,
                                as_supervised=True, try_gcs=True)
  mnist_dataset = (datasets['train'] if mode == tf.estimator.ModeKeys.TRAIN else
                   datasets['test'])

  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

  return mnist_dataset.map(scale).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

test = input_fn('test')
train = input_fn(tf.estimator.ModeKeys.TRAIN)

print(test)
print(train)

<BatchDataset shapes: ((?, 28, 28, 1), (?,)), types: (tf.float32, tf.int64)>
<BatchDataset shapes: ((?, 28, 28, 1), (?,)), types: (tf.float32, tf.int64)>


In [18]:
# 추정기는 tf.estimator.train_and_evaluation()를 사용하며, 데이터에 반복 작업하는 input_fn을 전달

tf.estimator.train_and_evaluate(
    classifier,
    train_spec=tf.estimator.TrainSpec(input_fn=input_fn),
    eval_spec=tf.estimator.EvalSpec(input_fn=input_fn)
)

NameError: name 'classifier' is not defined

In [19]:
import tensorflow as tf

x = tf.constant(4.0)
with tf.GradientTape(persistent=True) as g:
  g.watch(x)
  y = x * x
  z = y * y
dz_dx = g.gradient(z, x)  # 108.0 (4*x^3 at x = 4)
dy_dx = g.gradient(y, x)  # 6.0
print (dz_dx)
print (dy_dx)
del g  # Drop the reference to the tape

Tensor("AddN_1:0", shape=(), dtype=float32)
Tensor("AddN_2:0", shape=(), dtype=float32)
