In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

## shape - nd.array 객채의 형태  (길이) 

## ndim - nd.array  객체의 차원 

## size - nd.array  Element 의 갯수 
= ( shpae 의 모든 element 들의 곱 ) 

## vector (벡터)  - ndim=1 인 [ 1차원배열 ]

## matrix(매트리스) - ndim = 2 [ 2차원배열] 
-( 행 , 열 ) 길이가 같아야한다.

## tensor(텐서) - ndim=3 [3차원 배열]

In [9]:
v1 = np.array([1,2,5,6])

v1
v1.dtype
v1.shape # 0장 0행 4열 
v1.ndim
v1.size

array([1, 2, 5, 6])

dtype('int32')

(4,)

1

4

In [12]:
m1 = np.array([[1,2,5,6],
               [1,2,5,6],
               [1,2,5,6]])

m1
m1.dtype
m1.shape # 3행 4열 
m1.ndim
m1.size

array([[1, 2, 5, 6],
       [1, 2, 5, 6],
       [1, 2, 5, 6]])

dtype('int32')

(3, 4)

2

12

In [26]:
list_ar1 = [[1,2,5,8,],[1,2,5,8],[1,2,5,8]]

t1 = np.array([list_ar1,list_ar1])

t1
t1.dtype
t1.shape # 2장 ,3행 , 4열 
t1.ndim
t1.size

array([[[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]],

       [[1, 2, 5, 8],
        [1, 2, 5, 8],
        [1, 2, 5, 8]]])

dtype('int32')

(2, 3, 4)

3

24

In [36]:
# 실습 1 
class man():
    def __init__(self,en1):
        self.energy = en1
    def get_item(self):
        self.energy +=10
    def meet_lion(self):
        self.energy -=20
        
        
m1=man(100)
m1.energy
m1.get_item()
m1.energy
m1.meet_lion()
m1.energy

100

110

90

In [43]:
# 실습 2 

m1 = np.array([[6,5,4],[3,2,1]],np.int32)

m1
m1.dtype
m1.shape
m1.size
m1.nbytes

o1 = np.array([[6,5,4],[3,2,1]],np.float16)

o1
o1.dtype
o1.shape
o1.size
o1.nbytes

array([[6, 5, 4],
       [3, 2, 1]])

dtype('int32')

(2, 3)

6

24

array([[6., 5., 4.],
       [3., 2., 1.]], dtype=float16)

dtype('float16')

(2, 3)

6

12

# reshape 

## array 의 shape 크기를 변경해줌

In [52]:
ar1 = np.array([[1,2,3,4],[5,6,7,8]])

ar1
ar1.shape

ar2 = ar1.reshape(8,) # 8열 

ar2
ar2.shape

ar3 = ar2.reshape(4,2) # 4행 2열

ar3
ar3.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(2, 4)

array([1, 2, 3, 4, 5, 6, 7, 8])

(8,)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

(4, 2)

In [64]:
ar1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

ar1
ar1.shape

ar2 = ar1.reshape(4,3) # 4행 3열 

ar2
ar2.shape

ar3 = ar2.reshape(2,3,2) # 2장 3행 2열 

ar3
ar3.shape

# 다중 주석처리 ctrl + / 

ar4 = ar3.reshape(6,2)

ar4


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

(3, 4)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

(4, 3)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

(2, 3, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### reshape 의 변경크기는 행x열 의 최대이다 ex)  2x3x2 =12 12 안에서만 reshape 가능 

In [70]:
# -1 의 사용 

ar1 = np.array([[1,2,3],[4,5,6]])

ar1
ar1.shape

ar2 = ar1.reshape(-1,2)

ar2.shape

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

(3, 2)

## reshape -1 의 의미

- shape 크기가 6 일떄, 
- ( x , y ) 둘 중 하나만 실수를 입력하고 입력한 실수에 대해 맞는 element 개수 ( size ) 를 자동으로 지정해준다 
- element 개수를 -1 한다는 의미가 아님 ! 


## np.flatten() 

- 다차원 배열 을 무조건 1차원 배열으로 변환하는 내장함수

In [76]:
ar1 = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])

ar1
ar1.shape

ar2 = ar1.flatten()

ar2
ar2.shape

#  flatten() = reshape(-1,)

ar3 = ar1.reshape(-1,)

ar3
ar3.shape

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

(4, 4)

array([1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8])

(16,)

array([1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8])

(16,)

In [82]:
v1 = np.array([1,2,3,4,5,6])

v1

v2 = v1.reshape(2,3)

v2

v3 = v1.reshape(3,2)

v3 

v4 = v1.reshape(-1,1) # (6,1)

v4

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 과제 1 

In [91]:
l1 = [1,2]
l2 = [3,4]

ar1 = np.array([[l1,l2],[l1,l2],[l1,l2]], np.int16)

ar1
ar1.dtype


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

dtype('int16')

In [109]:
# reshape 을 사용해서 

l1 = [1,2]
l2 = [3,4]

ar1 = np.array([ [l1,l2],[l1,l2],[l1,l2]],np.int16)      
      
ar1
ar1.shape
ar1.dtype

ar2 = np.array([l1,l2,l1,l2,l1,l2] ,np.int32)

ar3 = ar2.reshape(3,2,2)

ar3

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

(3, 2, 2)

dtype('int16')

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])