In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random 

### element-wise

- shape 이 같을때 만 가능 
- shape 1 , shape 2  끼리 연산을 가능케함.

In [7]:
a1 = np.arange(6).reshape(2,3)
a2 = np.arange(10,16).reshape(2,-1)

a1
a2
# 같은 reshape 끼리 사칙연산 
a1+a2
a1*a2
a1-a2
a1/a2

array([[0, 1, 2],
       [3, 4, 5]])

array([[10, 11, 12],
       [13, 14, 15]])

array([[10, 12, 14],
       [16, 18, 20]])

array([[ 0, 11, 24],
       [39, 56, 75]])

array([[-10, -10, -10],
       [-10, -10, -10]])

array([[0.        , 0.09090909, 0.16666667],
       [0.23076923, 0.28571429, 0.33333333]])

In [16]:
# 4~40 range 의 각 element 의 제곱의 합 

ar1 =np.arange(4,40,4)

ar1
ar2 = ar1*ar1

ar2.sum()


array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

4560

### broadcasting

- shape 이 다를때, array 간의 shape 을 자동으로 맞춰줌


In [18]:
ar1 =np.arange(4,40,4)

ar1

# 사칙연산 
ar1+2
ar1*2
ar1/2
ar1-2
a1%2 # 나머지 구하기


array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38])

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72])

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34])

array([[0, 1, 0],
       [1, 0, 1]], dtype=int32)

### 매트릭스와 벡터와 연산 

- 매트릭스 +-*/ 벡터 시 ,   벡터 가 자동으로 매트릭스의 reshape 과 맞춰진 후 , 연산이 진행된다.
- 이를 벡터의 broadcasting 이라고한다.
- 만일 매트릭스 의 reshape 이 초과한다면 벡터는 자동화가 되지않는다 ( 즉, 무조건 자동화 되진 않는다 ) 

In [24]:
a1 = np.array([0,1,2]*4).reshape(4,3)
a2 = np.array([0,0,0,10,10,10,20,20,20,30,30,30]).reshape(4,3)

a1
a2

a1+a2

print('####')
a3 = np.array([0,1,2])

a2+a3

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

####


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### broadcasting 이 가능한 예

- Vector(n,) - scalr /  Matrix(n,m) - scalr / Matrix(n,m) - vector(m,)
- Matrix(n,m) - Matrix(1,m) / Matrix(n,m) - Matrix(n,1) / 
- tensor(p,n,m) - scalr / tensor(p,n,m) -vector(n,) / tensor(p,n,m) - matrix(1,m) / tensor(p,n,m) - matrix(n,m) 
- [[]] = 매트릭스  , [] = 벡터

In [29]:
a1 = np.arange(12).reshape(4,3)

# matrix 의 형태를 4x1 로 해도 broadcasting 이 가능하다.
a2 = np.random.randint(10 , size =(4,1) )

a1
a2

a1*a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[7],
       [1],
       [7],
       [1]])

array([[ 0,  7, 14],
       [ 3,  4,  5],
       [42, 49, 56],
       [ 9, 10, 11]])

## 실습

- 5의 배수 3으로 나눈 나머지의 합을 구하시오
- 조건 1 : numpy 패키지를 사용 O
- 조건 2 : numpy 패키지를 사용 X

In [44]:
a1 = np.arange(0,51,5)

#조건1
a1%3
np.sum(a1%3)

# 조건 2

s1=0

for i in range(51):
    if i %5 == 0:
        v1 = i%3
        s1 += v1 

array([0, 2, 1, 0, 2, 1, 0, 2, 1, 0, 2], dtype=int32)

11

## 실습 3

- (3,5) matrix 를 만들고 ,  각행에 다음과 같은 값을 더하시오
- 1. 0행 = 2, 1행 = 3  2행 = 1
- 2. 0~10 사이의 랜덤값을 3개 뽑아서 1과 같은 방식으로 각 행에 더하시오 

In [66]:
a1 = np.arange(15).reshape(3,5)

# 1번 
a1
a2 = np.array([2,3,1]).reshape(-1,1)
a2

a1+a2

# 2번 

a3 = np.random.randint(3, size = (3,1))
a3

a1+a3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[2],
       [3],
       [1]])

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [11, 12, 13, 14, 15]])

array([[0],
       [2],
       [1]])

array([[ 0,  1,  2,  3,  4],
       [ 7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15]])

### matrix 의 내적 ( dot product)

- 매트릭스1 의 행 과 매트릭스 2 의 형을  곱셈 하는것

In [90]:
m1 = np.arange(1,5).reshape(2,2)
m2 = np.arange(1,5).reshape(2,2)

m1
m2


print('#일반 곱하기#')
m1*m2
print('#내적 사용 곱셈#')

m1.dot(m2)
np.dot(m1,m2)

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [3, 4]])

#일반 곱하기#


array([[ 1,  4],
       [ 9, 16]])

#내적 사용 곱셈#


array([[ 7, 10],
       [15, 22]])

array([[ 7, 10],
       [15, 22]])

### transpose ( 뒤집기 ) 

- a1.T 또는 a1.transpose 로 호출
- 행 과 열 의 위치를 변환한다 3행2열 -> 2행3열 ( shape 이 앞뒤로 바뀐다 ) 

In [95]:
v1 = np.arange(10).reshape(2,5)
v1
v1.T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 3차원 tensor 의 transpose

In [155]:
t1 = np.arange(24).reshape(3,2,4)

t1
t1.shape

t2 = t1.T
t2
t2.shape

t3 = t1.reshape(4,2,3)
t3
t3.shape

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

(3, 2, 4)

array([[[ 0,  8, 16],
        [ 4, 12, 20]],

       [[ 1,  9, 17],
        [ 5, 13, 21]],

       [[ 2, 10, 18],
        [ 6, 14, 22]],

       [[ 3, 11, 19],
        [ 7, 15, 23]]])

(4, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

(4, 2, 3)

In [163]:
# 벡터를 transpose 

v1 = np.array([1,2,3,4])


v2 = v1.reshape(1,4) # v1 을 매트릭스로 변경 

v1
v2
v2.T # 매트릭스된 v2를 transpose 시킴

array([1, 2, 3, 4])

array([[1, 2, 3, 4]])

array([[1],
       [2],
       [3],
       [4]])

### concatenate ( 합치기 )

- 두 array 를 축에 따라 연결함 ( a1 + a2  ) 
- np.concatenate( (a1,a2, ...) ) , axis = 0 ) 

- 같은 차원의 배열만 합치기 가능
- axis 의 위치에 따라 에러 , non에러 이다.

In [104]:
# 벡터 의 concatenate 

v1 = np.arange(6)
v2 = np.arange(4,7)

v1
v2

v3 = np.concatenate((v1,v2,v1))
v3.shape

array([0, 1, 2, 3, 4, 5])

array([4, 5, 6])

(15,)

In [116]:
# 매트릭스의 concatenate 

m1 = np.arange(12).reshape(3,4)
m2 = np.arange(8).reshape(2,4)
m3 = np.arange(6).reshape(3,2)

m1
m2
m3

m4 = np.concatenate((m1,m2) , axis=0 )
m4

m5 = np.concatenate((m1,m3) , axis=1)
m5


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

array([[ 0,  1,  2,  3,  0,  1],
       [ 4,  5,  6,  7,  2,  3],
       [ 8,  9, 10, 11,  4,  5]])

In [126]:
#  tensor 의 concatenate

t1 = np.arange(24).reshape(2,4,3)
t2 = np.arange(12).reshape(1,4,3)
t3 = np.arange(8).reshape(4,1,2)
t4 = np.arange(24).reshape(4,3,2)

t1
t2
t3
t4
print('## concatenate t1 t2 ## ' )
np.concatenate((t1,t2))
print('## concatenate t1 t3 ## ' )

np.concatenate((t3,t4), axis=1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]],

       [[6, 7]]])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

## concatenate t1 t2 ## 


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

## concatenate t1 t3 ## 


array([[[ 0,  1],
        [ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[ 4,  5],
        [12, 13],
        [14, 15],
        [16, 17]],

       [[ 6,  7],
        [18, 19],
        [20, 21],
        [22, 23]]])

## 실습3 

- 벡터 reshape 과 concatenate 만을 사용하여 아래의 matrix2 를 만들어라 

In [154]:
a1 = np.arange(1,4)

# a1 벡터를 매트릭스 형변화 
a1 = a1.reshape(1,3)

# a1 매트릭스 3개 합쳐서 m1 변수 생성 
m1 = np.concatenate((a1,a1,a1))
m1
m1.shape

# a1 매트릭스를 뒤집기 ( transpose) 시키고 
m3 = a1.T

# m2 ( a1 매트릭스 *3 ) + m3 ( a1 매트릭스 뒤집은) 
m2 = np.concatenate((m1,m3), axis=1)
m2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

(3, 3)

array([[1, 2, 3, 1],
       [1, 2, 3, 2],
       [1, 2, 3, 3]])