In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

## 15016033 안효빈

In [30]:
# 과제 1 
m1 = np.arange(0.0,12.0,0.5).reshape(4,-1)

m1

m2 =m1[ : , 1: :2].reshape(-1)
m2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5]])

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5])

In [ ]:
ar1 = np.arange()

In [31]:
#과제 2 
m1 = np.random.choice(range(0,20,2),size=(6,6),replace=True)

m1

m2 = np.diag(m1).reshape(2,3)
m2

array([[ 2,  0,  0, 18, 14,  0],
       [ 2,  4,  4,  0, 14,  8],
       [12, 12, 10,  6,  2, 18],
       [ 2,  4,  0,  8,  0,  2],
       [ 0, 14, 18,  4,  4,  2],
       [18, 16,  8,  8, 12, 14]])

array([[ 2,  4, 10],
       [ 8,  4, 14]])