In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

### 과제 2 

    - 주어진 array 의 0행 = 5명의 수학점수
    - 1행 = 영어점수
    - 2행 = 나이  일때,
    - 영어보다 수학점수가 큰 사람의 나이의 합은?

In [42]:
a1 = np.random.randint(10 , size=(3,5))

a1
math = a1[0,:] # 수학점수
eng = a1[1,:] # 영어점수 
age = a1[2,:] # 나이

m = math>eng # 수학점수>영어점수 인 수학점수 element
m
age[m] # 수학점수>영어점수 인 나이 

array([[5, 5, 4, 8, 2],
       [7, 2, 8, 1, 8],
       [1, 4, 8, 7, 0]])

array([False,  True, False,  True, False])

array([4, 7])