In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

### fancy index 

    - index 를 사용해서 값을 추출하는 방법
    - boolean 은 T,F 
    - a1[b] [b] 의 인덱스위치에있는 a1 를 출력하라

In [5]:
a1 = np.array([1,2,3,4])
index = np.array([0,0,3,2])

a1
index

a1[index]

array([1, 2, 3, 4])

array([0, 0, 3, 2])

array([1, 1, 4, 3])

In [11]:
a1 = np.random.randint(1,11 ,size=(5,5))
a1
a1[[1,2,4],:] # [1,2,4] 행의 전체열을 가져오겠다
a1[:,[2,3,4]] # [2,3,4] 열의 전체 행을 가져오겠다.
a1[[0,0,0,0,1],:] # 0 행 4번 1행 1번
a1[:,[1,1,1,3]] # 

array([[ 6,  4,  4,  6,  5],
       [10,  6,  9,  2,  4],
       [ 6,  1,  6,  6,  2],
       [ 3,  3, 10,  9,  4],
       [ 2,  3,  4,  7,  7]])

array([[10,  6,  9,  2,  4],
       [ 6,  1,  6,  6,  2],
       [ 2,  3,  4,  7,  7]])

array([[ 4,  6,  5],
       [ 9,  2,  4],
       [ 6,  6,  2],
       [10,  9,  4],
       [ 4,  7,  7]])

array([[ 6,  4,  4,  6,  5],
       [ 6,  4,  4,  6,  5],
       [ 6,  4,  4,  6,  5],
       [ 6,  4,  4,  6,  5],
       [10,  6,  9,  2,  4]])

array([[4, 4, 4, 6],
       [6, 6, 6, 2],
       [1, 1, 1, 6],
       [3, 3, 3, 9],
       [3, 3, 3, 7]])

In [13]:
# 특정 element 

a1 = np.random.randint(100, size=(4,5))
a1

a1[[0,1,2],[2,3,2]] # (0,1) (1,3) (2,2) 을 가져오겠다.

array([[31, 13, 27,  3, 91],
       [83, 80, 45, 51, 77],
       [40, 65, 15, 78, 20],
       [59, 74, 14, 55, 70]])

array([27, 51, 15])

### fancy index 와 where

In [17]:
a1 = np.random.randint(100 , size=(4,5))
a1

b1 = np.where(a1>70)
b1

# fancy index 와 where
li = a1[b1]
li

# where 대신 list(zip ()) 을 쓰는경우

l2 =[]

for ii , jj in zip(b1[0],b1[1]):
    l2.append(a1[ii,jj])
l2

array([[ 9, 51, 21, 11, 38],
       [77, 56, 14, 44, 85],
       [89, 21,  5, 38, 57],
       [10, 83, 18,  7, 94]])

(array([1, 1, 2, 3, 3], dtype=int64), array([0, 4, 0, 1, 4], dtype=int64))

array([77, 85, 89, 83, 94])

[77, 85, 89, 83, 94]

### 실습


In [34]:
p1 = np.array([1000,2000,1500,2000])
o1 = np.array([1,1,3,2,3,4,1])

p1[o1-1]
p1[o1-1].sum()

array([1000, 1000, 1500, 2000, 1500, 2000, 1000])

10000

### 실습2

    - nan 이 없는 행들만 추출 하시오

In [58]:
a1 = np.random.randint(10 , size=(6,4))
a1 = a1.astype(float)

a1[[0,1,1,3],[1,1,2,3]]=np.nan
a1

np.isnan(a1)
a2 = np.isnan(a1).sum(axis=1)
a2
b1 = (a2 ==0)

a1[b1]

array([[ 8., nan,  1.,  5.],
       [ 0., nan, nan,  5.],
       [ 1.,  5.,  5.,  8.],
       [ 8.,  0.,  7., nan],
       [ 0.,  3.,  7.,  5.],
       [ 2.,  8.,  7.,  7.]])

array([[False,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

array([1, 2, 0, 1, 0, 0])

array([[1., 5., 5., 8.],
       [0., 3., 7., 5.],
       [2., 8., 7., 7.]])