In [50]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# W3 
    - numpy , dtype , ndim , size , nbytes 

## 실습 class 를 만들기 

In [3]:
class man():
    def __init__(self,en1):
        self.energy = en1
    def get_item(self):
        self.energy +=10
    def meet_lion(self):
        self.energy -=20
        
        
m1=man(100)
m1.energy
m1.get_item()
m1.energy
m1.meet_lion()
m1.energy

100

110

90

## 실습 , array 생성 후 shape, size , data type , byte 수 출력 하기

In [8]:
m1 = np.array([[6,5,4],[3,2,1]] , np.int32)

m1 = np.array([[6,5,4],[3,2,1]],np.int32)

m1
m1.dtype
m1.shape
m1.size
m1.nbytes

array([[6, 5, 4],
       [3, 2, 1]])

dtype('int32')

(2, 3)

6

24

## 실습 , array 생성 후 , reshape 하기

In [17]:
v1 = np.array([1,2,3,4,5,6])

v1
v1.reshape(2,3)
v1.reshape(3,2)
v1.reshape(-1,1)

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 과제 ar1, ar1.dtype 그리고 reshape

In [25]:
# list 변수를 사용해서 반복을 줄이자
ar1=np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]], dtype=np.int16)
ar1 = np.array( [ [ 1,2,3,4 ] , [1,2,3,4] , [1,2,3,4] ] , np.int16)

ar1
ar1.reshape(3,2,2)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int16)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

# W4
    - : arange , indexing & slicing , zeros , ones , identity , diag 

## 실습 , arange 와 reshape 을 사용해 3차원 tensor 만들고, 1,2차원으로 변환

In [29]:
ar1 = np.arange(1,61).reshape(5,3,4)

ar1
ar2_v=ar1.reshape(-1,)
ar2_m=ar1.reshape(1,-1)
ar2_v
ar2_m

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

## 실습 : index 를 이용해 인수 값 변환

In [30]:
# 1)
ar1=np.array(range(15)).reshape(3,5)
ar1
ar1[1,3]=1000
ar1

# 1)
ar1=np.array(range(60)).reshape(6,2,5)
ar1
ar1[3,0,-1]=1000
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7, 1000,    9],
       [  10,   11,   12,   13,   14]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]],

       [[  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19]],

       [[  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29]],

       [[  30,   31,   32,   33, 1000],
        [  35,   36,   37,   38,   39]],

       [[  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49]],

       [[  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59]]])

## 실습 : 슬라이싱을 이용해 인수 값 변환

In [31]:
# 1)
m1=np.arange(24).reshape(4,6)
a1=m1[2:,1:4]
a1

# 2)
m1[2:,1:4] = np.array([-1,-2,-3,-4,-5,-6]).reshape(2,3)
m1

array([[13, 14, 15],
       [19, 20, 21]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, -1, -2, -3, 16, 17],
       [18, -4, -5, -6, 22, 23]])

## 실습 : 슬라이싱을 이용해 인수값 변환 2 , step 파라미터

In [32]:
# 1)
m1=np.arange(24).reshape(2,12)
m1[:,::4]

# 2)
m2=np.arange(0,21,4).reshape(2,3)
m2

array([[ 0,  4,  8],
       [12, 16, 20]])

array([[ 0,  4,  8],
       [12, 16, 20]])

## 실습 : 4x4 matrix 를 0으로 초기화 한 후 데이터 변경

In [46]:
m1=np.zeros(shape=(4,4),dtype=np.int8)
m1
m1[1,:2] = np.array([2,2])
m1
m1[1,-1] = 2
m1
m1[:,2] = np.array([4,4,4,4])
m1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

array([[0, 0, 0, 0],
       [2, 2, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

array([[0, 0, 0, 0],
       [2, 2, 0, 2],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

array([[0, 0, 4, 0],
       [2, 2, 4, 2],
       [0, 0, 4, 0],
       [0, 0, 4, 0]], dtype=int8)

# 5W : 정규분포 , sum , max , armin , mean , median 

## 실습 : 정규분포 ( 평균 0 , 표준편차 2 ) 에서 sampling 하여 3x5 매트릭스 만든 후 슬라이싱


In [47]:
m1=np.random.normal(loc=0, scale=2.0, size=(3,5))
m1
m1[:,[0,2,3]]

array([[-0.73481623, -1.78855151, -0.5809093 ,  1.81989342, -2.23489756],
       [ 0.02859243,  0.10597433, -0.88528717, -1.34355307,  0.40513731],
       [-1.12097724, -3.07610292,  0.14173038, -2.11980792, -1.53138029]])

array([[-0.73481623, -0.5809093 ,  1.81989342],
       [ 0.02859243, -0.88528717, -1.34355307],
       [-1.12097724,  0.14173038, -2.11980792]])

## 실습 : 10~15 랜덤 정수에서 3차원 4x2x3 만들기 

In [48]:
t1=np.random.randint(10,16,size=(4,2,3))
t1
t1[2,:,:]

array([[[11, 12, 11],
        [10, 12, 14]],

       [[12, 12, 10],
        [12, 14, 13]],

       [[10, 11, 10],
        [11, 15, 11]],

       [[15, 14, 10],
        [12, 13, 14]]])

array([[10, 11, 10],
       [11, 15, 11]])

## 실습 : 0~5 까지 정수 3개를 random choice 후 , vector 만들기

In [49]:
t1=np.random.choice(np.arange(6),size=(3,),replace=False)
t1


array([1, 2, 4])

## 과제 : arange 를 사용해 float 배열 생성 , .5인 값만 슬라이싱 하기

In [40]:
a1 = np.arange(0.0,12.0,0.5).reshape(-1,4)

a1
a2 =a1[ : , 1: :2].reshape(-1)
a2

array([[ 0. ,  0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5]])

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5])

## 과제 : 랜덤인수 6x6 을 대각선 값만 빼와서 2x3 matrix 로 만들기 ( diag)

In [44]:
m1 = np.random.choice(range(0,20,2),size=(6,6),replace=True)

m1

m2 = np.diag(m1).reshape(2,3)
m2

array([[16,  6, 10,  2,  8,  8],
       [16,  4, 10, 18, 10,  6],
       [14,  8,  6, 12,  0,  4],
       [ 4, 12, 18,  0, 12,  6],
       [ 8, 12, 12, 18,  8, 12],
       [ 8,  4,  0,  2,  8,  2]])

array([[16,  4,  6],
       [ 0,  8,  2]])

## 실습 : 각 행별의 합 , 열 별 평균 구하기 ( axis = 0,1)

In [52]:
a1=np.arange(0,58,3).reshape(4,5)
a1
a1.sum()
a1.sum(axis=1)
a1.mean(axis=0)

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

570

array([ 30, 105, 180, 255])

array([22.5, 25.5, 28.5, 31.5, 34.5])

## 실습 : 매트릭스에 데이터 분할 이후, 평균 과 표준편차 계산

In [54]:
m1=np.arange(36).reshape(4,9)
m2=m1[:,2::3]
m1
m2
m2.mean(axis=0)
m2.std(axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

array([15.5, 18.5, 21.5])

array([10.0623059, 10.0623059, 10.0623059])

## 실습 : median 사용해서 각 장의 max, min 값 구하기

In [55]:
# 주어진 array
a1=np.random.randint(100, size=(3,4,5))
a1

# 1)
a2=np.median(a1, axis=2)
a2

# 2)
a3=a1.max(axis=1)
a3
a4=a3.max(axis=1)
a4

array([[[37, 50, 58, 73, 47],
        [82, 27, 19, 11,  6],
        [47, 40, 17, 98, 89],
        [49, 40, 41, 38, 71]],

       [[93,  4, 77, 97, 45],
        [11, 75, 75, 72, 22],
        [92, 12, 84, 81, 11],
        [30, 18, 56, 15, 31]],

       [[ 3, 12, 48, 30, 33],
        [59, 68, 52, 87, 26],
        [ 5, 65, 64,  7, 37],
        [37, 84, 64, 57, 59]]])

array([[50., 19., 47., 41.],
       [77., 72., 81., 30.],
       [30., 59., 37., 59.]])

array([[82, 50, 58, 98, 89],
       [93, 75, 84, 97, 45],
       [59, 84, 64, 87, 59]])

array([98, 97, 87])