In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
import pandas as pd

# 8W : Series index , dtype , name 

## 실습 : missing value 의 개수를 출력하시오

In [7]:
a1 =np.genfromtxt(fname= 'proj1.txt', dtype=float , delimiter='\t')

b1 = np.isnan(a1)


b1.sum(axis=1)

array([1, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1])

## 실습 : Series 만들기

In [8]:
s1 = pd.Series(np.arange(6,dtype=float), index=['a','1','b','2','c','3'] , name ='ds')
s1.index.name='ds_index'
s1

s1 = s1.astype(int)



ds_index
a    0.0
1    1.0
b    2.0
2    3.0
c    4.0
3    5.0
Name: ds, dtype: float64

ds_index
a    0
1    1
b    2
2    3
c    4
3    5
Name: ds, dtype: int32

# 9W : Series indexing slicing iloc , loc , nonnull()

## 실습 : values 를 활용해 3이상의 value 들의 평균을 구하시오

In [9]:
s1=pd.Series(np.random.randint(0,10,size=5), index=range(1,6))
s1
a1=s1.values
a1
a2=a1[a1>=3]
a2
a2.mean()

1    6
2    7
3    9
4    7
5    5
dtype: int32

array([6, 7, 9, 7, 5])

array([6, 7, 9, 7, 5])

6.8

## 실습 : loc 과 iloc 을 이용해 indexing

In [10]:
s1=pd.Series(np.arange(10), index=list('e1d2c3b4a5'))
s1
s1.loc['d']
s1.loc[['5']]
s1.loc['d':'b':2]

s1.iloc[2]
s1.iloc[[-1]]
s1.iloc[2:7:2]

e    0
1    1
d    2
2    3
c    4
3    5
b    6
4    7
a    8
5    9
dtype: int32

2

5    9
dtype: int32

d    2
c    4
b    6
dtype: int32

2

5    9
dtype: int32

d    2
c    4
b    6
dtype: int32

## 실습 : Series 에 *3 +1 이후 , 5의 배수로 나눈뒤 , np.sum() 하라

In [11]:
sr1=pd.Series(np.random.randint(10,size=10))
sr1
sr2=sr1*3+1
sr2
sr3=sr2[sr2%5==0]
sr3
ar1=np.array(sr3.index)
ar1.sum()

0    1
1    6
2    6
3    6
4    9
5    2
6    7
7    0
8    8
9    7
dtype: int32

0     4
1    19
2    19
3    19
4    28
5     7
6    22
7     1
8    25
9    22
dtype: int32

8    25
dtype: int32

8

## 실습 : Series 와 sort_values ( 가장 큰수 구하기)

In [12]:
sr1=pd.Series(np.random.randint(100,size=6), index=list('abcdef'))
sr1
sr1=sr1.sort_values(ascending=False)
sr1
sr1.index
sr1.index[1]

a    92
b    39
c    41
d    75
e    63
f    36
dtype: int32

a    92
d    75
e    63
c    41
b    39
f    36
dtype: int32

Index(['a', 'd', 'e', 'c', 'b', 'f'], dtype='object')

'd'

## Sr1 ,sr2 , sr3 공통적으로 있는 값 np.sum()

In [13]:
s1=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s1
s2=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s2
s3=pd.Series(np.random.randint(10,size=5), index=np.random.choice(list('abcdefgh'), size=5, replace=False))
s3

s4=s1+s2+s3
s4
s5=s4[s4.notnull()]
s5.sum()

c    0
e    2
f    9
g    2
d    0
dtype: int32

f    8
g    0
b    6
e    7
c    8
dtype: int32

c    7
g    9
d    6
h    7
e    7
dtype: int32

b     NaN
c    15.0
d     NaN
e    16.0
f     NaN
g    11.0
h     NaN
dtype: float64

42.0

## 실습 : 짝수인 data의 index 를 np.sum() 하시오

In [14]:
sr1=pd.Series(data=np.random.randint(100,size=5), index=np.random.randint(100,size=5))
print("## sr1")
sr1
print("## sr1%2==0")
sr2=sr1[sr1%2==0]
sr2
print("## index sum")
np.sum(sr2.index)

## sr1


21    95
11    18
74    54
26    54
44    56
dtype: int32

## sr1%2==0


11    18
74    54
26    54
44    56
dtype: int32

## index sum


155

## 실습 : 60보다 작은 값을 -100으로 변환하시오

In [15]:
sr1=pd.Series(data=np.random.randint(100,size=5), index=list('abcde'))
print("## sr1")
sr1
sr1[sr1>=60]=-100
sr1

## sr1


a    87
b    44
c    28
d    11
e    51
dtype: int32

a   -100
b     44
c     28
d     11
e     51
dtype: int32