In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
import numpy as np
import pandas as pd

## 내적 

In [15]:
A = np.array([[1,2,3],[4,5,6]]) # array 는 기본적으로 열 벡터  ( 2 X 3 )

A
A.shape

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

In [20]:
B = np.array([[1,2],[3,4],[5,6]]) # 3 X 2 

B
B.shape

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)

In [19]:
C = np.dot(A,B) # 결과값은 2 X 2 
C

array([[22, 28],
       [49, 64]])

## 3층 신경망 소프트맥스 

In [23]:
# 입력층 -> 1층 가중치 와 편향 

X = np.array([1.2, 0.6]) # input 
W1 = np.array([ [0.1 , 0.3 , 0.5] , [ 0.2 , 0.3 , 0.6] ]) # W11 , W12 , W13 / W12, W 22 , W32 가중치 , 소프트맥스
B1 = np.array([0.1 , 0.2 , 0.15 ]) # 편향 

X.shape
W1.shape
B1.shape

(2,)

(2, 3)

(3,)

In [26]:
def softmax(a):
    
    c = np.max(a)
    exp_a = np.exp(a-c) # 분자 
    
    sum_exp_a = np.sum(exp_a) # 분모 
    
    y = exp_a / sum_exp_a 
    return y 

In [24]:
from functions import sigmoid

A1 = np.dot(X,W1) + B1 
# 활성화 함수 적용 a -> z 
z1 = sigmoid(A1)

A1
z1

array([0.34, 0.74, 1.26])

array([0.58419052, 0.67699586, 0.77902611])

In [36]:
W2 = np.array([ [0.2 , 0.3 ] ,[ 0.5,0.1 ], [ 0.4,0.5 ] ])
B2 = np.array( [ 0.1 , 0.2 ])

###
 
A2 = np.dot(z1,W2) + B2 
z2 = sigmoid(A2)

A2
z2


array([0.48983876, 0.54068955])

array([0.62006845, 0.63197281])

In [38]:
## output

Y = softmax(z2)
Y

array([0.49702394, 0.50297606])